POST https://magicplugin.net/api/payment
Content-Type: application/json

{
  "userId": "1f6a6f0a-d2a2-499b-bba5-8492c9d3210d",
  "productId": "f110f4c0-4a16-4e76-97f0-5410ba25c75b",
  "card1": "5574",
  "card2": "1000",
  "card3": "1743",
  "card4": "5529",
  "exp_year": "27",
  "exp_month": "03",
  "customer": "호예준",
  "identity_num": "100108"
}

###